server:
  port: 8081 

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/carshow_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/carshow-realm 

keycloak:
  realm: carshow-realm
  auth-server-url: http://localhost:8080
  ssl-required: external
  resource: carshow-api 
  credentials:
    secret: your-client-secret 
  use-resource-role-mappings: true
  principal-attribute: preferred_username

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG 
    ru.carshow.security: DEBUG  