name: Emulator RISC-V
run-name: Testing ${{ github.repository }} by @${{ github.actor }}

on:
  create:
  repository_dispatch: 
  workflow_dispatch:
    inputs:
          start_dump:
              required: true
              type: string
              description: "start address for test task.bin"
              default: "0"
          size_dump:
              required: true
              type: string
              description: "size in bytes for test task.bin"
              default: "100"

jobs:
  buildtest:
    with:
      student_url:         ${{ github.repository }}
      student_ref:         ${{ github.sha }}
      start_dump:          ${{ inputs.start_dump }}
      size_dump:           ${{ inputs.size_dump }}
    uses: skkv-se-comp-arch/private-tools/.github/workflows/emulator.yml@main
    secrets: inherit            
