plugins {
    id 'org.springframework.boot' version '3.2.0' apply false
    id 'io.spring.dependency-management' version '1.1.4' apply false
}

subprojects {
    group = 'ru.carshow'
    version = '2.0.0'
    repositories { mavenCentral() }
}

tasks.register('integrationTest') {
    group = 'verification'
    description = 'Runs integration tests in all services'
    dependsOn ':order-service:integrationTest', ':storage-service:integrationTest'
}
