name: Optimizations
run-name: Testing ${{ github.repository }} by @${{ github.actor }}

on:
  create:
  repository_dispatch: 
  workflow_dispatch:
    inputs:
        image:
            type: choice
            default: 'hound0.pnm'
            description: test image
            options: 
            - in.pnm
            - in2.pnm
            - hound0.pnm
        kind:
            type: choice
            default: static
            description: schedule kind
            options: 
            - static
            - dynamic
        chunk_size:
            type: string
            default: '0'
            description: schedule chunk size

jobs:
  buildtest:
    with:
      student_url:         ${{ github.repository }}
      student_ref:         ${{ github.sha }}
      image:               ${{ inputs.image }}
      kind:                ${{ inputs.kind }}
      chunk_size:          ${{ inputs.chunk_size }}
    uses: skkv-se-comp-arch/private-tools/.github/workflows/optimizations.yml@main
    secrets: inherit            
